version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
        - /var/www:/var/www
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "80:80"
    links:
     - phpfpm
  restart: always

  memcached:
  image: memcached:latest
  restart: always

  phpfpm:
    build: .
    dockerfile: php-fpm/Dockerfile
    container_name: phpfpm
    volumes:
      - /var/www:/var/www
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      - ./php-fpm/www.conf:/etc/php/7.1/fpm/pool.d/www.conf
    links:
      - memcached
  restart: always